on: push
jobs:
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends clang libglib2.0-0 libglib2.0-dev pkgconf
      - run: clang $(pkgconf --cflags glib-2.0) test.c $(pkgconf --libs glib-2.0)
      - run: ./a.out
