on: push
jobs:
  test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    container: ubuntu:21.10
    steps:
      - uses: actions/checkout@v2
      - run: apt-get update && apt-get install -y ubuntu-dbgsym-keyring
      - run: echo "deb http://ddebs.ubuntu.com impish main restricted universe multiverse" > /etc/apt/sources.list.d/ddebs.list
      - run: apt-get update && apt-get install -y --no-install-recommends clang gdb libglib2.0-0-dbgsym libgstreamer1.0-0 libgstreamer1.0-0-dbgsym
      - run: clang -g test.c /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
      - run: gdb -batch -ex "run" -ex "thread apply all bt" ./a.out
